apiVersion: v2
name: ia-home-office-mock-api
home: https://github.com/hmcts/ia-home-office-mock-api
version: 0.0.2
description: A Helm chart for ia-home-office-mock-api App
maintainers:
  - name: HMCTS Immigration & Asylum Team
    email: ImmigrationandAsylum@HMCTS.NET
dependencies:
  - name: java
    version: 3.4.4
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
